# Generated by Django 4.2.20 on 2025-11-12 15:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=api.models.generate_access_code, max_length=14, unique=True, verbose_name='Код доступа')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('checker', 'Проверяющий'), ('support', 'Сопровождающий')], max_length=32, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Код доступа',
                'verbose_name_plural': 'Коды доступа',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название участка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название чек-листа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='api.area', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Чек-лист',
                'verbose_name_plural': 'Чек-листы',
            },
        ),
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели (понедельник)')),
                ('weeks_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество недель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'План на неделю',
                'verbose_name_plural': 'Планы на недели',
                'ordering': ['-week_start'],
                'unique_together': {('week_start',)},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID пользователя')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Администратор'), ('checker', 'Проверяющий'), ('support', 'Сопровождающий')], default='', help_text='Роль пользователя: Администратор | Проверяющий | Сопровождающий. Пусто — нет доступа.', max_length=32, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
        ),
        migrations.CreateModel(
            name='WeekAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.area', verbose_name='Участок')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.userprofile', verbose_name='Ответственный')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.scheduleweek', verbose_name='План недели')),
            ],
            options={
                'verbose_name': 'Назначение на день',
                'verbose_name_plural': 'Назначения на дни',
                'ordering': ['date', 'area_id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.checklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Вопрос чек-листа',
                'verbose_name_plural': 'Вопросы чек-листа',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weekassignment',
            constraint=models.UniqueConstraint(fields=('date', 'area'), name='unique_area_per_day'),
        ),
    ]
