# Generated by Django 4.2.20 on 2025-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'План на день',
                'verbose_name_plural': 'Планы на день',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='DayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_assignments', to='api.area', verbose_name='Участок')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.planday', verbose_name='План дня')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_assignments', to='api.userprofile', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Назначение (день)',
                'verbose_name_plural': 'Назначения (день)',
                'ordering': ['area_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dayassignment',
            constraint=models.UniqueConstraint(fields=('plan_day', 'area'), name='unique_area_per_plan_day'),
        ),
    ]
