# Generated by Django 4.2.20 on 2025-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_planday_alter_userprofile_options_dayassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planday',
            options={'ordering': ['-date'], 'verbose_name': 'Расписание на день', 'verbose_name_plural': 'Расписания на день'},
        ),
        migrations.AlterModelOptions(
            name='scheduleweek',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weekassignment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='weekassignment',
            name='unique_area_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleweek',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weekassignment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='weekassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weekassignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weekassignment',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='weekassignment',
            name='week',
        ),
        migrations.RemoveField(
            model_name='scheduleweek',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduleweek',
            name='week_start',
        ),
        migrations.RemoveField(
            model_name='scheduleweek',
            name='weeks_count',
        ),
    ]
