# Generated by Django 4.2.20 on 2025-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_planday_options_alter_scheduleweek_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayassignment',
            options={'ordering': ['area_id', 'id'], 'verbose_name': 'Запись расписания', 'verbose_name_plural': 'Записи расписания'},
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обхода по участку'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Обход по участку выполнен'),
        ),
        migrations.AddField(
            model_name='planday',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обхода'),
        ),
        migrations.AddField(
            model_name='planday',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Обход выполнен'),
        ),
    ]
