# Generated by Django 4.2.20 on 2025-11-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dayassignment_options_dayassignment_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='watcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watched_areas', to='api.userprofile', verbose_name='Смотрящий'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='support_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время сопровождающего'),
        ),
    ]
