# Generated by Django 4.2.20 on 2025-11-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_area_watcher_dayassignment_support_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='watcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watched_areas', to='api.userprofile', verbose_name='Сопровождающий'),
        ),
        migrations.CreateModel(
            name='SupportProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_time', models.TimeField(verbose_name='Предложенное время')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_proposals', to='api.area', verbose_name='Участок')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_support_proposals', to='api.userprofile', verbose_name='Кем решено')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_proposals', to='api.planday', verbose_name='План дня')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_support_proposals', to='api.userprofile', verbose_name='Инициатор (проверяющий)')),
            ],
            options={
                'verbose_name': 'Предложение времени',
                'verbose_name_plural': 'Предложения времени',
                'ordering': ['-created_at'],
            },
        ),
    ]
