# Generated by Django 4.2.20 on 2025-11-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_area_watcher_supportproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference/', verbose_name='Эталонное фото'),
        ),
        migrations.CreateModel(
            name='InspectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='api.area', verbose_name='Участок')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_sessions', to='api.userprofile', verbose_name='Проверяющий')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='api.planday', verbose_name='План дня')),
            ],
            options={
                'verbose_name': 'Сессия обхода',
                'verbose_name_plural': 'Сессии обхода',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=True, verbose_name='Соответствует')),
                ('defect_photo', models.ImageField(blank=True, null=True, upload_to='defects/', verbose_name='Фото дефекта')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Отвечено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.checklistquestion', verbose_name='Вопрос')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.inspectionsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ по обходу',
                'verbose_name_plural': 'Ответы по обходу',
            },
        ),
    ]
